version: '3.4'
services:
  db:
    image: danielsmanioto/rest-pring-boot
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always 
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: mysql_rest-java-spring-boot
    ports: 
      - "3308:3308"
    networks:
      - ds-network
  rest-java-spring-boot:
    image: danielsmanioto/rest-java-spring-boot
    restart: always
    build: ./
    working_dir: ./
    environment: 
      TZ: Americana/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: gradle clean buildRun
    links: 
      - db
    networks:
      - ds-network
networks:
  ds-network: 
    driver: bridge 
